blank_issues_enabled: false
contact_links:
  - name: Deppenpfostierung Community Support
    url: https://github.com/orgs/deppenpfostierung/discussions
    about: Please ask and answer questions here.